Вариант 6-1
PIVAB/java-kanban pull request #1
Opened 2024-04-20 14:33 UTC by PIVAB

2024-04-21 20:11 UTC, Fleaman777 requested changes

2024-04-21 20:11 UTC, Fleaman777 commented on src/model/Epic.java
> +    private ArrayList<Integer> subtaskIdList = new ArrayList<>();
Используй интерфейс List для объявления subtaskIdList. Это даст больше гибкости при изменении типа списка

2024-04-21 20:11 UTC, Fleaman777 commented on src/service/Node.java
> +public class Node<E> {
в принципе  этот класс можно сделать внутренним для InMemoryHistoryManager, тк его основной "потребитель" находится там

2024-04-21 20:11 UTC, Fleaman777 commented on test/service/HistoryManagerTest.java
> +    void inHistoryShouldChangeTask() {
в тестах джава код стайл так же применим, название тест метода должно начинаться с глагола

2024-04-22 08:10 UTC, PIVAB commented on src/model/Epic.java
> +    private ArrayList<Integer> subtaskIdList = new ArrayList<>();
Исправлено

2024-04-22 08:13 UTC, PIVAB commented on src/service/Node.java
> +public class Node<E> {
Исправлено

2024-04-22 08:44 UTC, PIVAB commented on test/service/HistoryManagerTest.java
> +    void inHistoryShouldChangeTask() {
Исправлено

2024-04-22 20:15 UTC, Fleaman777 requested changes
Необходимо пофиксить билд

2024-04-24 12:32 UTC, closed without merging